defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
  - scope:
      path: "docs"
    values:
      layout: single
      sidebar:
        nav: "docs"
  - scope:
      path: "wiki"
    values:
      layout: single
      sidebar:
        nav: "wiki"

exclude:
  - db
  - node_modules
  - src
  - Dockerfile
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

#remote_theme: "mmistakes/minimal-mistakes"
# possible other theme: https://jekyllthemes.io/theme/feeling-responsive

# Theme configuration
title: Restreamer
repository: "datarhei/restreamer"
minimal_mistakes_skin: "contrast"

encoding: utf-8
baseurl: "/restreamer"
