defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "docs"
    values:
      layout: docs
      tab: docs
  -
    scope:
      path: "wiki"
    values:
      layout: wiki
      tab: wiki

sass:
  sass_dir: _sass
  style: :compressed

baseurl: "/restreamer"
lsi: false
safe: true
source: .
