defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
  - scope:
      path: "docs"
    values:
      layout: single
      sidebar:
        nav: "docs"
  - scope:
      path: "wiki"
    values:
      layout: single
      sidebar:
        nav: "wiki"

exclude:
  - db
  - node_modules
  - src
  - Dockerfile
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

#remote_theme: "mmistakes/minimal-mistakes"
# possible other theme: https://jekyllthemes.io/theme/feeling-responsive

# Theme configuration
title: Restreamer
repository: "datarhei/restreamer"
minimal_mistakes_skin: "air"
twitter:
  username: "datarhei"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/datarhei"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/datarhei"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/datarhei/restreamer"

encoding: utf-8
baseurl: "/restreamer"
