defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "docs"
    values:
      layout: docs
      tab: docs
  - scope:
      path: "wiki"
    values:
      layout: wiki
      tab: wiki

exclude:
  - db
  - node_modules
  - src
  - Dockerfile
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

encoding: utf-8
baseurl: "/restreamer"
